global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['44.202.224.95:9100','34.207.173.254:9100','3.90.177.253:9100']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['44.202.224.95:9200','34.207.173.254:9200','3.90.177.253:9200']
