global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'exporter'
    static_configs:
    - targets: ['18.209.174.168:9100']
  - job_name: 'advisor'
    static_configs:
    - targets: ['18.209.174.168:9200']
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:role/newec2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-DevOps-7f3f11f5-ECSAutoScalingGroup-180fDCCCPRMx
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:role/newec2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-DevOps-7f3f11f5-ECSAutoScalingGroup-180fDCCCPRMx
