global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['http://monitor_ec2_public_ip:9090/targets'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:role/forEC2fromECS
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-DevOps-7f3f11f5-ECSAutoScalingGroup-MilNE1gFgVOk
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:role/forEC2fromECS
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-DevOps-7f3f11f5-ECSAutoScalingGroup-MilNE1gFgVOk