global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost

  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - endpoint: "ec2.us-east-1.amazonaws.com"
        region: "us-east-1"
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:role/ECSroleEC2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-cluster-da68bf3a-ECSAutoScalingGroup-oEDkkKx0GvXt

  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - endpoint: "ec2.us-east-1.amazonaws.com"
        region: "us-east-1"
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:role/ECSroleEC2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-cluster-da68bf3a-ECSAutoScalingGroup-oEDkkKx0GvXt

    params:
      ACCESS_KEY_ID: /parameter/ACCESS_KEY_ID
      SECRET_ACCESS_KEY: /parameter/SECRET_ACCESS_KEY
