global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['3.219.218.158:9100','3.218.143.62:9100','184.72.166.10:9100']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['3.219.218.158:9200','3.218.143.62:9200','184.72.166.10:9200']

