global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecs_node_exporter'
    ec2_sd_configs:
      - port: 9100
        filters:
          - name: tag:ecs:cluster
            values:
              - cluster
          - name: tag:ecs:service
            values:
              - YourECSServiceName

  - job_name: 'ecs_cadvisor'
    ec2_sd_configs:
      - port: 9200
        filters:
          - name: tag:ecs:cluster
            values:
              - cluster
          - name: tag:ecs:service
            values:
              - YourECSServiceName
              

