global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['44.200.70.225:9100','34.229.207.2:9100']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['44.200.70.225:9200','34.229.207.2:9200']
