global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['34.200.253.245:9100 ']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['54.158.220.234:9200']
  - job_name: 'web-application'
    static_configs:
    - targets: ['34.200.253.245:9999']
