global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2-node-exporter'
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9100 # Assuming your node-exporter runs on this port
        filters:
          - name: "tag:aws:autoscaling:groupName"
            values:
              - "Infra-ECS-Cluster-Clusterfortest-d90bddc7-ECSAutoScalingGroup-St8hjDSjKUNo"

  - job_name: 'ec2-cadvisor-exporter'
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9200 # Assuming your cadvisor-exporter runs on this port
        filters:
          - name: "tag:aws:autoscaling:groupName"
            values:
              - "Infra-ECS-Cluster-Clusterfortest-d90bddc7-ECSAutoScalingGroup-St8hjDSjKUNo"
