global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - region: 'us-east-1'
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:instance-profile/ecsInstanceRole
        filters:
        - name: Name
          values:
          - ECS Instance - dev-cluster
  - job_name: ecs_CAdvisor
    ec2_sd_configs: 
      - region: 'us-east-1'
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:instance-profile/ecsInstanceRole
        filters:
        - name: Name
          values:
          - ECS Instance - dev-cluster
