global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:role/ec2, arn:aws:iam::381491829424:role/ecs
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-Dev-cluster-85c1fdf0-ECSAutoScalingGroup-8pmkhwN41O9d
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:role/ec2, arn:aws:iam::381491829424:role/ecs 
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - Infra-ECS-Cluster-Dev-cluster-85c1fdf0-ECSAutoScalingGroup-8pmkhwN41O9d
  - job_name: 'web-application'
    static_configs:
      - targets: ['34.200.253.245:9999']
