global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['3.230.1.71','54.80.17.152:9100','3.210.197.253:9100']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['3.230.1.71:9200','54.80.17.152:9200','3.210.197.253:9200']
