global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::381491829424:role/ECSroleEC2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - arn:aws:autoscaling:us-east-1:381491829424:autoScalingGroup:6761545e-ba5d-4169-be38-fbf487f09217:autoScalingGroupName/Infra-ECS-Cluster-cluster-da68bf3a-ECSAutoScalingGroup-PcjMjar6wCiw
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::381491829424:role/ECSroleEC2
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - arn:aws:autoscaling:us-east-1:381491829424:autoScalingGroup:6761545e-ba5d-4169-be38-fbf487f09217:autoScalingGroupName/Infra-ECS-Cluster-cluster-da68bf3a-ECSAutoScalingGroup-PcjMjar6wCiw
