global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['44.204.132.199:9100','3.218.156.171:9100','35.153.100.149:9100']
  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['44.204.132.199:9200','3.218.156.171:9200','35.153.100.149:9200']



scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['54.175.91.30:9100','34.200.248.20:9100']

  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['54.175.91.30:9200','34.200.248.20:9200']