global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] 
  - job_name: 'ec2-node-exporter'
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9100 
        filters:
          - name: "tag:aws:autoscaling:groupName"
            values:
              - "Infra-ECS-Cluster-Ecscluster-9831bc4b-ECSAutoScalingGroup-0OW0bh2uyX6F"

  - job_name: 'ec2-cadvisor-exporter'
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9200 
        filters:
          - name: "tag:aws:autoscaling:groupName"
            values:
              - "Infra-ECS-Cluster-Ecscluster-9831bc4b-ECSAutoScalingGroup-0OW0bh2uyX6F"
