apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app  : my-k8s-application
    env  : prod
    owner: PiterKononihin
spec:
  selector:
    matchLabels:
      project: myapp1
  template:
    metadata:
      labels:
        project: myapp1
    spec:
      containers:
        - name : web-myapp1
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/piterbog:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
