
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-03f9f5982b918c4a2"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0332008f9914214e9" }
      us-east-1-1b: { id: "subnet-06694c26ecc357635" }
   private:
      us-east-1-1a: { id: "subnet-0dee7e9269ddb40ae" }
      us-east-1-1b: { id: "subnet-07ecbb25fd288dd19" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  