
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0ae7d19c1e9784d69"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-013ba1792040bfe5b" }
      us-east-1-1b: { id: "subnet-08e297260ad98a056" }
   private:
      us-east-1-1a: { id: "subnet-01e9c6e16783607ab" }
      us-east-1-1b: { id: "subnet-059e17551be4c3bb1" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  - name             : workers-2
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true  