
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0b0231287c75133e8"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0ac8b384bb209238d" }
      us-east-1-1b: { id: "subnet-008674710ba1fe3f0" }
   private:
      us-east-1-1a: { id: "subnet-03483496470929f6f" }
      us-east-1-1b: { id: "subnet-0809542cfe232add7" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  - name             : workers-2
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true  