
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0c94be47a59c0e671"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-012a21ddb005df976" }
      us-east-1-1b: { id: "subnet-072186624e54c8696" }
   private:
      us-east-1-1a: { id: "subnet-060abd3e5d8db4efa" }
      us-east-1-1b: { id: "subnet-04012d9908f0265c2" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  - name             : workers-2
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true  