
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-00577c65e850cc2ee"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0bc4f1dd575d7506b" }
      us-east-1-1b: { id: "subnet-0873acb1faa4273a8" }
   private:
      us-east-1-1a: { id: "subnet-0aaa72cf4ae9d3a56" }
      us-east-1-1b: { id: "subnet-0e29c9cd6f560e7c7" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
