
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0209fa24f9142239b"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0fbc4c128d66cdc85" }
      us-east-1-1b: { id: "subnet-0dbcb2350b63fbd72" }
   private:
      us-east-1-1a: { id: "subnet-002ab794c9228029d" }
      us-east-1-1b: { id: "subnet-0cc4f9182b686f648" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  