
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0e7abb5748ef85f31"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0c2adc44cec746533" }
      us-east-1-1b: { id: "subnet-0e193fa16b9d5b9b2" }
   private:
      us-east-1-1a: { id: "subnet-0255bdbb4f9f16bec" }
      us-east-1-1b: { id: "subnet-08b1445879a31f2f2" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  