
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-048b3c65bfdae9909"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0eb06d27c51515011" }
      us-east-1-1b: { id: "subnet-0f1516e4abc528741" }
   private:
      us-east-1-1a: { id: "subnet-03a62711e40d5d045" }
      us-east-1-1b: { id: "subnet-00aded8ae99a215ba" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  