
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0309eaa461a851d13"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-04aab94785fafc7be" }
      us-east-1-1b: { id: "subnet-0110ff078a0c67513" }
   private:
      us-east-1-1a: { id: "subnet-0218e930c5ac54eda" }
      us-east-1-1b: { id: "subnet-05057739401ff6572" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
