
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-03daaf84f9c384417"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-02756a667ae987be3" }
      us-east-1-1b: { id: "subnet-07b6f230839bed952" }
   private:
      us-east-1-1a: { id: "subnet-08c50d8656158984f" }
      us-east-1-1b: { id: "subnet-0d7541ec8471b06d9" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  