
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-03f9f5982b918c4a2"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-080f0c3225dd24842" }
      us-east-1-1b: { id: "subnet-0f1516e4abc528741" }
   private:
      us-east-1-1a: { id: "subnet-061428cf44e4ada17" }
      us-east-1-1b: { id: "subnet-0d6fd64f32efe124b" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  