
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-07cc4f3e3dc20fde5"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0403d24d6b3178fa0" }
      us-east-1-1b: { id: "subnet-0344176e2a5669365" }
   private:
      us-east-1-1a: { id: "subnet-094d72a7ec3bada4f" }
      us-east-1-1b: { id: "subnet-0ed30d1360a395569" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
