
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-06cc182ad4581b34f"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0f1d1ac4cce3c2bee" }
      us-east-1-1b: { id: "subnet-0547fed60b54f6a67" }
   private:
      us-east-1-1a: { id: "subnet-0046c5879af8ac914" }
      us-east-1-1b: { id: "subnet-00bd0a1bdcb1e359f" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

