
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0c94e8e1a024fabb2"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-079ed810f757a3ca0" }
      us-east-1-1b: { id: "subnet-01dab896d6c4c2917" }
   private:
      us-east-1-1a: { id: "subnet-0102b9a2c95a21f3b" }
      us-east-1-1b: { id: "subnet-088366ead0605bcdc" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
