
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-094140afe2b2e0092"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-0826507aa8cb0d4eb" }
      us-east-1-1b: { id: "subnet-031082654f17c477e" }
   private:
      us-east-1-1a: { id: "subnet-0d3bd7b0122e89cc8" }
      us-east-1-1b: { id: "subnet-067143602602586dd" }

nodeGroups:
  - name             : workers-1
    instanceType     : t2.medium
    desiredCapacity  : 2
    privateNetworking: true    

  # - name             : workers-2
  #   instanceType     : t2.medium
  #   desiredCapacity  : 2
  #   privateNetworking: true  