
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
# eksctl update cluster -f eks-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-cluster
  version: "1.29"
  region : us-east-1
  
vpc:
 id : "vpc-0609d1c1cfaf74fe4"
 subnets:
   public:
      us-east-1-1a: { id: "subnet-014e1cb321c96d5f4" }
      us-east-1-1b: { id: "subnet-0973f7429e291d71b" }
   private:
      us-east-1-1a: { id: "subnet-06c63a86ef1a598f0" }
      us-east-1-1b: { id: "subnet-0d63b203b4add6683" }

nodeGroups:
  - name             : workers
    instanceType     : t2.medium
    desiredCapacity  : 4
    privateNetworking: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
