apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Перенаправление с HTTP на HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Принудительное перенаправление на HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Протокол бэкэнда HTTPS

spec:
  rules:
   - host: "app.piterbog.com"
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kuber-service-1
                port:
                  number: 80

    
