apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
   - host: a0328100174664ea9999d9f2159cac67-99cec48b55703a4f.elb.us-east-1.amazonaws.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kuber-service-1
                port: 
                  number: 80