apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  tls:
  - hosts:
    - app.piterbog.com
    secretName: arn:aws:acm:us-east-1:381491829424:certificate/9e16dc87-be99-4341-b0f0-d2dbbe8ee63e
  rules:
  - host: "app.piterbog.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kuber-service-1
            port: 
              number: 80
              
    
