name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html'
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get build date and time
        id: datetime
        run: echo "::set-output name=datetime::$(date +%Y-%m-%d_%H-%M-%S)"

      - name: build Doker image
        run: |
          docker build -t myapp1:latest .
          docker tag myapp1:latest 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:latest
          docker tag myapp1:latest 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }}
      
      - name: Отправка образа в ECR
        run: |
          docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:latest
          docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }}
      