name: Сборка и загрузка Docker образа

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html' 
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Настройка учетных данных AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Вход в ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Получение даты и времени сборки
        id: datetime
        run: echo "::set-output name=datetime::$(date +%Y-%m-%d_%H-%M-%S)"

      - name: Сборка Docker образа
        run: |
          docker build -t myapp:-latest${{ steps.datetime.outputs.datetime }} .
          docker tag myapp:-latest${{ steps.datetime.outputs.datetime }} 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:latest-${{ steps.datetime.outputs.datetime }}

      - name: Отправка образа в ECR
        run: |
         docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:-latest${{ steps.datetime.outputs.datetime }}
