name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html'
      - 'Web/**/*.css'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t myapp1:latestv .
          docker tag myapp1:latestv ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/piterbog:latestv
      
      - name: Push image to ECR
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/piterbog:latestv

      # - name: Setup kubectl
      #   run: |
      #     export KUBECONFIG=<(echo "$KUBE_CONFIG_DATA")
      
      # - name: Setup kubectl
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg
      #     curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      #     echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      #     sudo apt-get update
      #     sudo apt-get install -y kubectl

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f kubernetes/deploy-svc-1.yaml
          
