name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html'
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Build Date and Time
        id: datetime
        run: echo "::set-output name=datetime::$(date +%Y-%m-%d_%H-%M-%S)"

      - name: Build Docker Image
        run: |
          docker build -t myapp1:latest .
          docker tag myapp1:latest 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:latest
          docker tag myapp1:latest 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }}

      - name: Push Image to ECR
        run: |
          docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:latest 
          docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }}
          
          

   

          

      # - name: Настроить kubectl
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
    
      # - name: Развернуть на EKS
      #   run: kubectl apply -f deployment.yaml
