name: Сборка и загрузка Docker образа

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html' 
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Настройка учетных данных AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Enter to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Получение даты сборки
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Сборка Docker образа
        run: |
          docker build -t myapp:v1 .
          docker tag myapp:v1 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:v1-${{ steps.date.outputs.date }}

      - name: Push image to ECR
        run: |
         docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:v1-${{ steps.date.outputs.date }}
