name: CI/CD Пайплайн

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html'
      - 'Web/**/*.css'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Получить код
      uses: actions/checkout@v2
      
    - name: Войти в AWS ECR
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Построить Docker образ
      run: docker build -t myapp100 .
      
    - name: Пометить Docker образ
      run: docker tag myapp100:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:latest
      
    - name: Отправить Docker образ в ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:latest
      
    # - name: Настроить kubectl
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Развернуть на EKS
    #   run: kubectl apply -f deployment.yaml


      