name: Build Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html' 
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Настройка учетных данных AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Enter to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Получение текущей версии образа
        id: get-image-version
        run: echo "::set-output name=version::$(cat image_version.txt)"

      - name: Увеличение версии образа
        id: increment-version
        run: echo "::set-output name=version::$(($(echo '${{ steps.get-image-version.outputs.version }}' | cut -c 2-) + 1))"

      - name: Запись новой версии образа в файл
        run: echo "v${{ steps.increment-version.outputs.version }}" > image_version.txt

      - name: Сборка Docker образа
        run: |
          docker build -t myapp:v${{ steps.increment-version.outputs.version}} .
          docker tag myapp:v${{ steps.increment-version.outputs.version}} 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:v${{ steps.increment-version.outputs.version }}

      - name: Push image to ECR
        run: |
         docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:v${{ steps.increment-version.outputs.version }}
