name: Сборка и загрузка Docker образа

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html' 
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Настройка учетных данных AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Enter to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Получение версии из репозитория
        id: version
        run: echo "::set-output name=version::$(git describe --tags --always)"

      - name: Сборка Docker образа
        run: |
          docker build -t myapp:${{ steps.version.outputs.version }} .
          docker tag myapp:${{ steps.version.outputs.version }} 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.version.outputs.version }}

      - name: Push image to ECR
        run: |
         docker push 381491829424.dkr.ecr.us-east-1.amazonaws.com/piterbog:${{ steps.version.outputs.version }}

