name: Сборка и загрузка Docker образа

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**/*.html'
      - 'Web/**/*.css'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v2

      - name: Настройка учетных данных AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Получить дату и время сборки
        id: datetime

      - name: Сборка Docker образа
        run: |
          docker build -t myapp1:latest .
          docker tag myapp1:latest 381491829424.dkr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:latest
          docker tag myapp1:latest 381491829424.dkr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }}

      - name: Пушить образ в ECR
        id: push-image
        run: |
          docker push 381491829424.dkr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:latest || true
          docker push 381491829424.dkr.${{ secrets.AWS_REGION }}.amazonaws.com/piterbog:${{ steps.datetime.outputs.datetime }} || true

      - name: Проверка успешности загрузки Docker образа
        if: ${{ failure() }}
        run: |
          echo "Ошибка загрузки Docker образа"
          

          

      # - name: Настроить kubectl
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
    
      # - name: Развернуть на EKS
      #   run: kubectl apply -f deployment.yaml
