name: Run ECS Task

on:
  push:
    branches:
      - main
    paths:
      - 'bash-script/run_ecs_task.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run ECS Task
        run: |
          chmod +x bash-script/run_ecs_task.sh
          ./bash-script/run_ecs_task.sh web-app-hello-from-ecs-cluster staging


