name: Run ECS Task

on:
  push:
    branches:
      - main
    paths:
      - 'bash-script/script.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Run ECS Task
        run: |
          chmod +x script.sh
          ./script.sh web-app-hello-from-ecs-cluster Ecs_cluster
