name: Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Decrypt Terraform state file from S3 if encrypted
        run: |
            aws s3 cp s3://vpc-piter-kononihin-terraform/dev/vpc/terraform.tfstate.enc .
            aws kms decrypt --ciphertext-blob fileb://terraform.tfstate.enc --output text --query Plaintext | base64 --decode > terraform.tfstate
        working-directory: ./My-First-Apolication/My-First-Application/Terraform/.terraform/terraform.tfstate

        
      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
